# Generated by Django 5.2.8 on 2025-11-15 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentToLoMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_weight', models.FloatField(default=0.0, help_text="Assessment'ın LO'ya katkı yüzdesi (0-100)")),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lo_mappings', to='core.assessment')),
                ('learning_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_mappings', to='core.learningoutcome')),
            ],
            options={
                'verbose_name': 'Assessment to LO Mapping',
                'verbose_name_plural': 'Assessment to LO Mappings',
                'unique_together': {('assessment', 'learning_outcome')},
            },
        ),
    ]
