# Generated by Django 6.0 on 2025-12-27 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_course_approval_status_course_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='approval_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('approval_request', 'Approval Request'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20),
        ),
    ]
