# Generated by Django 6.0 on 2025-12-27 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_enrollment'),
        ('core', '0005_alter_course_approval_status_and_more'),
    ]

    operations = [
    ]
